<?php
/**
 * Category1
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace iNew\Rest6_1\Model;

use \ArrayAccess;

/**
 * Category1 Class Doc Comment
 *
 * @category    Class
 * @description enum to represent the different categories of responses
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Category1 {
    const BUSINESS_ERROR = 'BUSINESS_ERROR';
    const OTHER = 'OTHER';
    const SUCCESSFUL = 'SUCCESSFUL';
    const TECHNICAL_ERROR = 'TECHNICAL_ERROR';
    

    
}

