<?php
/**
 * OfflineRatingInfosEvent
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace iNew\Rest6_1\Model;

use \ArrayAccess;

/**
 * OfflineRatingInfosEvent Class Doc Comment
 *
 * @category    Class
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OfflineRatingInfosEvent implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'OfflineRatingInfosEvent';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'mms_rating_info' => '\iNew\Rest6_1\Model\RatingInfo',
        'sms_rating_info' => '\iNew\Rest6_1\Model\RatingInfo',
        'subscriber' => '\iNew\Rest6_1\Model\SubscriberIdentifier'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'mms_rating_info' => 'mmsRatingInfo',
        'sms_rating_info' => 'smsRatingInfo',
        'subscriber' => 'subscriber'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'mms_rating_info' => 'setMmsRatingInfo',
        'sms_rating_info' => 'setSmsRatingInfo',
        'subscriber' => 'setSubscriber'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'mms_rating_info' => 'getMmsRatingInfo',
        'sms_rating_info' => 'getSmsRatingInfo',
        'subscriber' => 'getSubscriber'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['mms_rating_info'] = isset($data['mms_rating_info']) ? $data['mms_rating_info'] : null;
        $this->container['sms_rating_info'] = isset($data['sms_rating_info']) ? $data['sms_rating_info'] : null;
        $this->container['subscriber'] = isset($data['subscriber']) ? $data['subscriber'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets mms_rating_info
     * @return \iNew\Rest6_1\Model\RatingInfo
     */
    public function getMmsRatingInfo()
    {
        return $this->container['mms_rating_info'];
    }

    /**
     * Sets mms_rating_info
     * @param \iNew\Rest6_1\Model\RatingInfo $mms_rating_info A detailed rating information with pricing for MMS Event traffic type
     * @return $this
     */
    public function setMmsRatingInfo($mms_rating_info)
    {
        $this->container['mms_rating_info'] = $mms_rating_info;

        return $this;
    }

    /**
     * Gets sms_rating_info
     * @return \iNew\Rest6_1\Model\RatingInfo
     */
    public function getSmsRatingInfo()
    {
        return $this->container['sms_rating_info'];
    }

    /**
     * Sets sms_rating_info
     * @param \iNew\Rest6_1\Model\RatingInfo $sms_rating_info A detailed rating information with pricing for SMS Event traffic type
     * @return $this
     */
    public function setSmsRatingInfo($sms_rating_info)
    {
        $this->container['sms_rating_info'] = $sms_rating_info;

        return $this;
    }

    /**
     * Gets subscriber
     * @return \iNew\Rest6_1\Model\SubscriberIdentifier
     */
    public function getSubscriber()
    {
        return $this->container['subscriber'];
    }

    /**
     * Sets subscriber
     * @param \iNew\Rest6_1\Model\SubscriberIdentifier $subscriber The subscription the rating applies to
     * @return $this
     */
    public function setSubscriber($subscriber)
    {
        $this->container['subscriber'] = $subscriber;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\iNew\Rest6_1\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\iNew\Rest6_1\ObjectSerializer::sanitizeForSerialization($this));
    }
}


