<?php
/**
 * AbstractDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * AbstractDetailsTest Class Doc Comment
 *
 * @category    Class */
// * @description Abstract base class common to all details.&lt;br&gt;
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AbstractDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AbstractDetails"
     */
    public function testAbstractDetails()
    {

    }

    /**
     * Test attribute "service_channel"
     */
    public function testPropertyServiceChannel()
    {

    }

    /**
     * Test attribute "service_user"
     */
    public function testPropertyServiceUser()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

}
