<?php
/**
 * AccessKeyStoreTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * AccessKeyStoreTest Class Doc Comment
 *
 * @category    Class */
// * @description AccessKeyStore
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccessKeyStoreTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AccessKeyStore"
     */
    public function testAccessKeyStore()
    {

    }

    /**
     * Test attribute "access_role"
     */
    public function testPropertyAccessRole()
    {

    }

    /**
     * Test attribute "access_rules"
     */
    public function testPropertyAccessRules()
    {

    }

    /**
     * Test attribute "assigned_to"
     */
    public function testPropertyAssignedTo()
    {

    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {

    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {

    }

    /**
     * Test attribute "parameter_restrictions"
     */
    public function testPropertyParameterRestrictions()
    {

    }

    /**
     * Test attribute "properties"
     */
    public function testPropertyProperties()
    {

    }

    /**
     * Test attribute "provider_id"
     */
    public function testPropertyProviderId()
    {

    }

    /**
     * Test attribute "retailer_key"
     */
    public function testPropertyRetailerKey()
    {

    }

}
