<?php
/**
 * ActiveOverdraftDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * ActiveOverdraftDetailsTest Class Doc Comment
 *
 * @category    Class */
// * @description ActiveOverdraftDetails
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ActiveOverdraftDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ActiveOverdraftDetails"
     */
    public function testActiveOverdraftDetails()
    {

    }

    /**
     * Test attribute "activation_date"
     */
    public function testPropertyActivationDate()
    {

    }

    /**
     * Test attribute "activation_fee"
     */
    public function testPropertyActivationFee()
    {

    }

    /**
     * Test attribute "after_grace_period_fee"
     */
    public function testPropertyAfterGracePeriodFee()
    {

    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {

    }

    /**
     * Test attribute "currency_name"
     */
    public function testPropertyCurrencyName()
    {

    }

    /**
     * Test attribute "currency_unit_relation"
     */
    public function testPropertyCurrencyUnitRelation()
    {

    }

    /**
     * Test attribute "eligible_amount"
     */
    public function testPropertyEligibleAmount()
    {

    }

    /**
     * Test attribute "grace_period"
     */
    public function testPropertyGracePeriod()
    {

    }

    /**
     * Test attribute "grace_period_end_date"
     */
    public function testPropertyGracePeriodEndDate()
    {

    }

    /**
     * Test attribute "loan_amount"
     */
    public function testPropertyLoanAmount()
    {

    }

    /**
     * Test attribute "outstanding_amount"
     */
    public function testPropertyOutstandingAmount()
    {

    }

}
