<?php
/**
 * AdminEventChargingParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * AdminEventChargingParametersTest Class Doc Comment
 *
 * @category    Class */
// * @description AdminEventChargingParameters
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdminEventChargingParametersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AdminEventChargingParameters"
     */
    public function testAdminEventChargingParameters()
    {

    }

    /**
     * Test attribute "charging_trigger"
     */
    public function testPropertyChargingTrigger()
    {

    }

    /**
     * Test attribute "event_name"
     */
    public function testPropertyEventName()
    {

    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {

    }

    /**
     * Test attribute "roaming"
     */
    public function testPropertyRoaming()
    {

    }

    /**
     * Test attribute "service_code"
     */
    public function testPropertyServiceCode()
    {

    }

    /**
     * Test attribute "service_type"
     */
    public function testPropertyServiceType()
    {

    }

    /**
     * Test attribute "session_begin_time_stamp"
     */
    public function testPropertySessionBeginTimeStamp()
    {

    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {

    }

}
