<?php
/**
 * CurrencyTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * CurrencyTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description &lt;p&gt; User: michael Date: Sep 22, 2009 Time: 12:38:34 PM &lt;/p&gt;
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CurrencyTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CurrencyType"
     */
    public function testCurrencyType()
    {

    }

    /**
     * Test attribute "charging_unit"
     */
    public function testPropertyChargingUnit()
    {

    }

    /**
     * Test attribute "charging_unit_relation"
     */
    public function testPropertyChargingUnitRelation()
    {

    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "units"
     */
    public function testPropertyUnits()
    {

    }

}
