<?php
/**
 * HistoryEventTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * HistoryEventTest Class Doc Comment
 *
 * @category    Class */
// * @description The history event represents an entry in a subscriber&#39;s history.&lt;br&gt; It contains all relevant data to be search plus all additional details and charges set that occurred for that specific event.&lt;br&gt; The charges and details are stored in String representation; the ApiUtil class provides methods to deserialize these.&lt;br&gt;
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HistoryEventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "HistoryEvent"
     */
    public function testHistoryEvent()
    {

    }

    /**
     * Test attribute "charges"
     */
    public function testPropertyCharges()
    {

    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {

    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {

    }

    /**
     * Test attribute "event_date"
     */
    public function testPropertyEventDate()
    {

    }

    /**
     * Test attribute "operation"
     */
    public function testPropertyOperation()
    {

    }

    /**
     * Test attribute "result_code"
     */
    public function testPropertyResultCode()
    {

    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {

    }

    /**
     * Test attribute "sub_type"
     */
    public function testPropertySubType()
    {

    }

    /**
     * Test attribute "subscription_id"
     */
    public function testPropertySubscriptionId()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

}
