<?php
/**
 * LoanInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * LoanInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description LoanInfo
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LoanInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "LoanInfo"
     */
    public function testLoanInfo()
    {

    }

    /**
     * Test attribute "administration_fee"
     */
    public function testPropertyAdministrationFee()
    {

    }

    /**
     * Test attribute "expiry_date"
     */
    public function testPropertyExpiryDate()
    {

    }

    /**
     * Test attribute "loan_detail"
     */
    public function testPropertyLoanDetail()
    {

    }

}
