<?php
/**
 * PolicyInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * PolicyInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description Contains the information about the data usage policy including the PCC rule id and if applicable the expire date and/or the amount of remaining bytes defining until when this policy is valid
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PolicyInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "PolicyInfo"
     */
    public function testPolicyInfo()
    {

    }

    /**
     * Test attribute "pcc_rule_id"
     */
    public function testPropertyPccRuleId()
    {

    }

    /**
     * Test attribute "remaining_bytes"
     */
    public function testPropertyRemainingBytes()
    {

    }

    /**
     * Test attribute "valid_to"
     */
    public function testPropertyValidTo()
    {

    }

}
