<?php
/**
 * ReferralCodeInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * ReferralCodeInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description Defines the referral code, its valid period and the reward associated with this code
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReferralCodeInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ReferralCodeInfo"
     */
    public function testReferralCodeInfo()
    {

    }

    /**
     * Test attribute "data_only_reward"
     */
    public function testPropertyDataOnlyReward()
    {

    }

    /**
     * Test attribute "recurring"
     */
    public function testPropertyRecurring()
    {

    }

    /**
     * Test attribute "ref_code"
     */
    public function testPropertyRefCode()
    {

    }

    /**
     * Test attribute "reward"
     */
    public function testPropertyReward()
    {

    }

    /**
     * Test attribute "usage_limit"
     */
    public function testPropertyUsageLimit()
    {

    }

    /**
     * Test attribute "valid_period"
     */
    public function testPropertyValidPeriod()
    {

    }

}
