<?php
/**
 * SelectableQuotaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * SelectableQuotaTest Class Doc Comment
 *
 * @category    Class */
// * @description SelectableQuota
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SelectableQuotaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SelectableQuota"
     */
    public function testSelectableQuota()
    {

    }

    /**
     * Test attribute "bonus_message"
     */
    public function testPropertyBonusMessage()
    {

    }

    /**
     * Test attribute "bonus_threshold_amount"
     */
    public function testPropertyBonusThresholdAmount()
    {

    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {

    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {

    }

    /**
     * Test attribute "currency_name"
     */
    public function testPropertyCurrencyName()
    {

    }

    /**
     * Test attribute "currency_unit_relation"
     */
    public function testPropertyCurrencyUnitRelation()
    {

    }

    /**
     * Test attribute "range_max_amount"
     */
    public function testPropertyRangeMaxAmount()
    {

    }

    /**
     * Test attribute "range_min_amount"
     */
    public function testPropertyRangeMinAmount()
    {

    }

    /**
     * Test attribute "selectable_max_amount"
     */
    public function testPropertySelectableMaxAmount()
    {

    }

    /**
     * Test attribute "selectable_min_amount"
     */
    public function testPropertySelectableMinAmount()
    {

    }

    /**
     * Test attribute "shared"
     */
    public function testPropertyShared()
    {

    }

}
