<?php
/**
 * SharedPlanDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * SharedPlanDetailsTest Class Doc Comment
 *
 * @category    Class */
// * @description Common class with all properties specific for shared plans
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SharedPlanDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SharedPlanDetails"
     */
    public function testSharedPlanDetails()
    {

    }

    /**
     * Test attribute "add_subscriber_fee"
     */
    public function testPropertyAddSubscriberFee()
    {

    }

    /**
     * Test attribute "add_subscriber_quota"
     */
    public function testPropertyAddSubscriberQuota()
    {

    }

    /**
     * Test attribute "number_of_free_subscribers"
     */
    public function testPropertyNumberOfFreeSubscribers()
    {

    }

}
