<?php
/**
 * SimDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * SimDetailsTest Class Doc Comment
 *
 * @category    Class */
// * @description SimDetails
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SimDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SimDetails"
     */
    public function testSimDetails()
    {

    }

    /**
     * Test attribute "current_iccid"
     */
    public function testPropertyCurrentIccid()
    {

    }

    /**
     * Test attribute "current_imsi"
     */
    public function testPropertyCurrentImsi()
    {

    }

    /**
     * Test attribute "current_msisdn"
     */
    public function testPropertyCurrentMsisdn()
    {

    }

    /**
     * Test attribute "donor_carrier"
     */
    public function testPropertyDonorCarrier()
    {

    }

    /**
     * Test attribute "pin1"
     */
    public function testPropertyPin1()
    {

    }

    /**
     * Test attribute "pin2"
     */
    public function testPropertyPin2()
    {

    }

    /**
     * Test attribute "previous_iccid"
     */
    public function testPropertyPreviousIccid()
    {

    }

    /**
     * Test attribute "previous_imsi"
     */
    public function testPropertyPreviousImsi()
    {

    }

    /**
     * Test attribute "previous_msisdn"
     */
    public function testPropertyPreviousMsisdn()
    {

    }

    /**
     * Test attribute "puk1"
     */
    public function testPropertyPuk1()
    {

    }

    /**
     * Test attribute "puk2"
     */
    public function testPropertyPuk2()
    {

    }

    /**
     * Test attribute "recipient_carrier"
     */
    public function testPropertyRecipientCarrier()
    {

    }

    /**
     * Test attribute "sim_type"
     */
    public function testPropertySimType()
    {

    }

}
