<?php
/**
 * SponsorPoolInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iNew\Rest6_1;

/**
 * SponsorPoolInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description Basic information about sponsor pool for subscriber. Pool is created either manually or on shared plan/bundle activation by the owner and deleted either manually or on subscriber expiration. Only owner of the pool (subscriber with ADMIN role) can add or remove subscribers from the pool
/**
 * @package     iNew\Rest6_1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SponsorPoolInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SponsorPoolInfo"
     */
    public function testSponsorPoolInfo()
    {

    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {

    }

    /**
     * Test attribute "sponsor"
     */
    public function testPropertySponsor()
    {

    }

    /**
     * Test attribute "subscribers"
     */
    public function testPropertySubscribers()
    {

    }

}
