<?php
/**
 * VoiceMailApiTest
 * PHP version 5
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open REST API
 *
 * The Open REST API provides all available methods for integrators to access the I-New platform
 *
 * OpenAPI spec version: 6.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace iNew\Rest6_1;

use \iNew\Rest6_1\Configuration;
use \iNew\Rest6_1\ApiClient;
use \iNew\Rest6_1\ApiException;
use \iNew\Rest6_1\ObjectSerializer;

/**
 * VoiceMailApiTest Class Doc Comment
 *
 * @category Class
 * @package  iNew\Rest6_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VoiceMailApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for vmsSubscriberServiceGetSubscriberBoxState
     *
     * retrieves the voice mail box state.
     *
     */
    public function testVmsSubscriberServiceGetSubscriberBoxState()
    {

    }

    /**
     * Test case for vmsSubscriberServiceGetSubscriberBoxStateSubscription
     *
     * retrieves the voice mail box state.
     *
     */
    public function testVmsSubscriberServiceGetSubscriberBoxStateSubscription()
    {

    }

    /**
     * Test case for vmsSubscriberServiceSetSubscriberBoxState
     *
     * sets the voice mail box state.
     *
     */
    public function testVmsSubscriberServiceSetSubscriberBoxState()
    {

    }

    /**
     * Test case for vmsSubscriberServiceSetSubscriberBoxStateSubscription
     *
     * sets the voice mail box state.
     *
     */
    public function testVmsSubscriberServiceSetSubscriberBoxStateSubscription()
    {

    }

}
